### ISSUE TITLE
Just making sure

### ISSUE THREAD

**Issue by MrIbby** [WolfieWaffle/Hardcore-Torches#2]
Not sure if you've seen it, but Unlit Torches is licensed under the [GPLv3](http://www.gnu.org/licenses/gpl-3.0.html). It's an open-source license; you can find a [handy list of do's and don'ts](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)) at tldrlegal.com.

**Comment by WolfieWaffle** [comment]
OK, I'll look at it. My mod is getting further away from the original mod, the only thing that is copied at the moment is some of the textures. I looked at the do and don'ts, but it didn't seem to fit mods very well. I guess by "provide original" it could mean to provide a link to the original mod, which I was going to do anyways when I got the mod out of alpha and make a page for it somewhere. But I'll keep this in mind. I didn't see it on the page, so thanks :)

**Comment by MrIbby** [comment]
Most of the time you should be able to find licenses in repositories.

Unlit Torches repo: https://github.com/pelepmc/Unlit-Torches

**Comment by WolfieWaffle** [comment]
Oh wow. I didn't even see it had a repository. It's right on the front page :P

**Comment by MrIbby** [comment]
Yep :P
